name: Auto Semantic Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          latest=$(git tag --sort=-v:refname | grep '^v' | head -n 1)
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Bump Version (Patch)
        id: bump
        run: |
          latest=${{ steps.get_tag.outputs.latest }}
          if [ -z "$latest" ]; then
            next="v1.0.0"
          else
            IFS='.' read -r major minor patch <<< "${latest#v}"
            patch=$((patch + 1))
            next="v$major.$minor.$patch"
          fi
          echo "tag=$next" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump.outputs.tag }}
          git push origin ${{ steps.bump.outputs.tag }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.tag }}
          release_name: Release ${{ steps.bump.outputs.tag }}
          body: |
            Automated release for ${{ steps.bump.outputs.tag }}
          draft: false
          prerelease: false
